refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: rolling_file
    path: "log/chain_proxy.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb  # 文件达到10MB时轮转
      roller:
        kind: fixed_window
        pattern: "log/chain_proxy.{}.log"
        base: 1
        count: 5
root:
  level: info
  appenders:
    - stdout
    - file
