refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: rolling_file
    path: "logs/chain_proxy.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb # when the file size exceeds 10mb, a rollover will be triggered
      roller:
        kind: fixed_window
        pattern: "logs/chain_proxy.{}.log"
        base: 1
        count: 5
root:
  level: info
  appenders:
    - stdout
    - file
