version: 1
threads: 8
grace_period_seconds: 10
pid_file: /tmp/chain-proxy.pid
upgrade_sock: /tmp/chain-proxy.sock
Chains:
  - Name: optimism
    Listen: 8017
    Interval: 15
    BlockGap: 50
    Nodes:
      - Address: http://127.0.0.1:11160
        Priority: 1
      - Address: https://optimism-sepolia.infura.io/v3/559af310b68646d8accf0cf36111f2eb
        Priority: 0
    HealthCheck:
      Path: ""
      Method: POST