Chains:
  - Name: optimism
    Listen: 1017
    Interval: 5
    BlockGap: 50
    Nodes:
      - Address: https://rpc.ankr.com/optimism
        Priority: 1
      - Address: https://mainnet.optimism.io/
        Priority: 0
    HealthCheck:
      Path: ""
      Method: POST