version: 1
threads: 8
grace_period_seconds: 10
pid_file: /tmp/chain-proxy.pid
upgrade_sock: /tmp/chain-proxy.sock
Chains:
  - Name: ripple
    Protocol: "jsonrpc"
    Listen: 8018
    Interval: 15
    BlockGap: 50
    ChainType: "ripple"
    Nodes:
      - Address: http://10.19.18.143:5005
        Priority: 2
      - Address: https://s2.ripple.com:51234/
        Priority: 1
      - Address: https://s1.ripple.com:51234/
        Priority: 1
    HealthCheck:
      Path: ""
      Method: POST
Monitor:
    Listen: 7899
    System: "wallet"