Chains:
  - Name: solana
    Listen: 1017
    Interval: 20
    BlockGap: 20
    Nodes:
      - Address: https://tiniest-wandering-flower.solana-mainnet.quiknode.pro
        Priority: 1
      - Address: https://api.mainnet-beta.solana.com
        Priority: 0
    HealthCheck:
      Path: /health
      Method: GET
  - Name: smartchain
    Listen: 1090
    Interval: 20
    BlockGap: 20
    Nodes:
      - Address: https://palpable-newest-county.bsc.quiknode.pro
        Priority: 1
      - Address: http://127.0.0.1:11006
        Priority: 0
    HealthCheck:
      Path: /health
      Method: GET