Chains:
  - Name: optimism
    Listen: 1017
    Interval: 20
    BlockGap: 20
    Nodes:
      - Address: https://practical-green-butterfly.optimism.quiknode.pro/d02f8d49bde8ccbbcec3c9a8962646db998ade83
        Priority: 1
      - Address: https://mainnet.optimism.io/
        Priority: 0
    HealthCheck:
      Path: ""
      Method: POST